// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package gotdbot

type UpdateType string

const (
	UpdateTypeAccentColors                             UpdateType = "updateAccentColors"
	UpdateTypeActiveEmojiReactions                     UpdateType = "updateActiveEmojiReactions"
	UpdateTypeActiveGiftAuctions                       UpdateType = "updateActiveGiftAuctions"
	UpdateTypeActiveLiveLocationMessages               UpdateType = "updateActiveLiveLocationMessages"
	UpdateTypeActiveNotifications                      UpdateType = "updateActiveNotifications"
	UpdateTypeAgeVerificationParameters                UpdateType = "updateAgeVerificationParameters"
	UpdateTypeAnimatedEmojiMessageClicked              UpdateType = "updateAnimatedEmojiMessageClicked"
	UpdateTypeAnimationSearchParameters                UpdateType = "updateAnimationSearchParameters"
	UpdateTypeApplicationRecaptchaVerificationRequired UpdateType = "updateApplicationRecaptchaVerificationRequired"
	UpdateTypeApplicationVerificationRequired          UpdateType = "updateApplicationVerificationRequired"
	UpdateTypeAttachmentMenuBots                       UpdateType = "updateAttachmentMenuBots"
	UpdateTypeAuthorizationState                       UpdateType = "updateAuthorizationState"
	UpdateTypeAutosaveSettings                         UpdateType = "updateAutosaveSettings"
	UpdateTypeAvailableMessageEffects                  UpdateType = "updateAvailableMessageEffects"
	UpdateTypeBasicGroup                               UpdateType = "updateBasicGroup"
	UpdateTypeBasicGroupFullInfo                       UpdateType = "updateBasicGroupFullInfo"
	UpdateTypeBusinessConnection                       UpdateType = "updateBusinessConnection"
	UpdateTypeBusinessMessageEdited                    UpdateType = "updateBusinessMessageEdited"
	UpdateTypeBusinessMessagesDeleted                  UpdateType = "updateBusinessMessagesDeleted"
	UpdateTypeCall                                     UpdateType = "updateCall"
	UpdateTypeChatAccentColors                         UpdateType = "updateChatAccentColors"
	UpdateTypeChatAction                               UpdateType = "updateChatAction"
	UpdateTypeChatActionBar                            UpdateType = "updateChatActionBar"
	UpdateTypeChatActiveStories                        UpdateType = "updateChatActiveStories"
	UpdateTypeChatAddedToList                          UpdateType = "updateChatAddedToList"
	UpdateTypeChatAvailableReactions                   UpdateType = "updateChatAvailableReactions"
	UpdateTypeChatBackground                           UpdateType = "updateChatBackground"
	UpdateTypeChatBlockList                            UpdateType = "updateChatBlockList"
	UpdateTypeChatBoost                                UpdateType = "updateChatBoost"
	UpdateTypeChatBusinessBotManageBar                 UpdateType = "updateChatBusinessBotManageBar"
	UpdateTypeChatDefaultDisableNotification           UpdateType = "updateChatDefaultDisableNotification"
	UpdateTypeChatDraftMessage                         UpdateType = "updateChatDraftMessage"
	UpdateTypeChatEmojiStatus                          UpdateType = "updateChatEmojiStatus"
	UpdateTypeChatFolders                              UpdateType = "updateChatFolders"
	UpdateTypeChatHasProtectedContent                  UpdateType = "updateChatHasProtectedContent"
	UpdateTypeChatHasScheduledMessages                 UpdateType = "updateChatHasScheduledMessages"
	UpdateTypeChatIsMarkedAsUnread                     UpdateType = "updateChatIsMarkedAsUnread"
	UpdateTypeChatIsTranslatable                       UpdateType = "updateChatIsTranslatable"
	UpdateTypeChatLastMessage                          UpdateType = "updateChatLastMessage"
	UpdateTypeChatMember                               UpdateType = "updateChatMember"
	UpdateTypeChatMessageAutoDeleteTime                UpdateType = "updateChatMessageAutoDeleteTime"
	UpdateTypeChatMessageSender                        UpdateType = "updateChatMessageSender"
	UpdateTypeChatNotificationSettings                 UpdateType = "updateChatNotificationSettings"
	UpdateTypeChatOnlineMemberCount                    UpdateType = "updateChatOnlineMemberCount"
	UpdateTypeChatPendingJoinRequests                  UpdateType = "updateChatPendingJoinRequests"
	UpdateTypeChatPermissions                          UpdateType = "updateChatPermissions"
	UpdateTypeChatPhoto                                UpdateType = "updateChatPhoto"
	UpdateTypeChatPosition                             UpdateType = "updateChatPosition"
	UpdateTypeChatReadInbox                            UpdateType = "updateChatReadInbox"
	UpdateTypeChatReadOutbox                           UpdateType = "updateChatReadOutbox"
	UpdateTypeChatRemovedFromList                      UpdateType = "updateChatRemovedFromList"
	UpdateTypeChatReplyMarkup                          UpdateType = "updateChatReplyMarkup"
	UpdateTypeChatRevenueAmount                        UpdateType = "updateChatRevenueAmount"
	UpdateTypeChatTheme                                UpdateType = "updateChatTheme"
	UpdateTypeChatTitle                                UpdateType = "updateChatTitle"
	UpdateTypeChatUnreadMentionCount                   UpdateType = "updateChatUnreadMentionCount"
	UpdateTypeChatUnreadPollVoteCount                  UpdateType = "updateChatUnreadPollVoteCount"
	UpdateTypeChatUnreadReactionCount                  UpdateType = "updateChatUnreadReactionCount"
	UpdateTypeChatVideoChat                            UpdateType = "updateChatVideoChat"
	UpdateTypeChatViewAsTopics                         UpdateType = "updateChatViewAsTopics"
	UpdateTypeConnectionState                          UpdateType = "updateConnectionState"
	UpdateTypeContactCloseBirthdays                    UpdateType = "updateContactCloseBirthdays"
	UpdateTypeDefaultBackground                        UpdateType = "updateDefaultBackground"
	UpdateTypeDefaultPaidReactionType                  UpdateType = "updateDefaultPaidReactionType"
	UpdateTypeDefaultReactionType                      UpdateType = "updateDefaultReactionType"
	UpdateTypeDeleteMessages                           UpdateType = "updateDeleteMessages"
	UpdateTypeDiceEmojis                               UpdateType = "updateDiceEmojis"
	UpdateTypeDirectMessagesChatTopic                  UpdateType = "updateDirectMessagesChatTopic"
	UpdateTypeEmojiChatThemes                          UpdateType = "updateEmojiChatThemes"
	UpdateTypeFavoriteStickers                         UpdateType = "updateFavoriteStickers"
	UpdateTypeFile                                     UpdateType = "updateFile"
	UpdateTypeFileAddedToDownloads                     UpdateType = "updateFileAddedToDownloads"
	UpdateTypeFileDownload                             UpdateType = "updateFileDownload"
	UpdateTypeFileDownloads                            UpdateType = "updateFileDownloads"
	UpdateTypeFileGenerationStart                      UpdateType = "updateFileGenerationStart"
	UpdateTypeFileGenerationStop                       UpdateType = "updateFileGenerationStop"
	UpdateTypeFileRemovedFromDownloads                 UpdateType = "updateFileRemovedFromDownloads"
	UpdateTypeForumTopic                               UpdateType = "updateForumTopic"
	UpdateTypeForumTopicInfo                           UpdateType = "updateForumTopicInfo"
	UpdateTypeFreezeState                              UpdateType = "updateFreezeState"
	UpdateTypeGiftAuctionState                         UpdateType = "updateGiftAuctionState"
	UpdateTypeGroupCall                                UpdateType = "updateGroupCall"
	UpdateTypeGroupCallMessageLevels                   UpdateType = "updateGroupCallMessageLevels"
	UpdateTypeGroupCallMessagesDeleted                 UpdateType = "updateGroupCallMessagesDeleted"
	UpdateTypeGroupCallMessageSendFailed               UpdateType = "updateGroupCallMessageSendFailed"
	UpdateTypeGroupCallParticipant                     UpdateType = "updateGroupCallParticipant"
	UpdateTypeGroupCallParticipants                    UpdateType = "updateGroupCallParticipants"
	UpdateTypeGroupCallVerificationState               UpdateType = "updateGroupCallVerificationState"
	UpdateTypeHavePendingNotifications                 UpdateType = "updateHavePendingNotifications"
	UpdateTypeInstalledStickerSets                     UpdateType = "updateInstalledStickerSets"
	UpdateTypeLanguagePackStrings                      UpdateType = "updateLanguagePackStrings"
	UpdateTypeLiveStoryTopDonors                       UpdateType = "updateLiveStoryTopDonors"
	UpdateTypeManagedBot                               UpdateType = "updateManagedBot"
	UpdateTypeMessageContainsUnreadPollVotes           UpdateType = "updateMessageContainsUnreadPollVotes"
	UpdateTypeMessageContent                           UpdateType = "updateMessageContent"
	UpdateTypeMessageContentOpened                     UpdateType = "updateMessageContentOpened"
	UpdateTypeMessageEdited                            UpdateType = "updateMessageEdited"
	UpdateTypeMessageFactCheck                         UpdateType = "updateMessageFactCheck"
	UpdateTypeMessageInteractionInfo                   UpdateType = "updateMessageInteractionInfo"
	UpdateTypeMessageIsPinned                          UpdateType = "updateMessageIsPinned"
	UpdateTypeMessageLiveLocationViewed                UpdateType = "updateMessageLiveLocationViewed"
	UpdateTypeMessageMentionRead                       UpdateType = "updateMessageMentionRead"
	UpdateTypeMessageReaction                          UpdateType = "updateMessageReaction"
	UpdateTypeMessageReactions                         UpdateType = "updateMessageReactions"
	UpdateTypeMessageSendAcknowledged                  UpdateType = "updateMessageSendAcknowledged"
	UpdateTypeMessageSendFailed                        UpdateType = "updateMessageSendFailed"
	UpdateTypeMessageSendSucceeded                     UpdateType = "updateMessageSendSucceeded"
	UpdateTypeMessageSuggestedPostInfo                 UpdateType = "updateMessageSuggestedPostInfo"
	UpdateTypeMessageUnreadReactions                   UpdateType = "updateMessageUnreadReactions"
	UpdateTypeNewBusinessCallbackQuery                 UpdateType = "updateNewBusinessCallbackQuery"
	UpdateTypeNewBusinessMessage                       UpdateType = "updateNewBusinessMessage"
	UpdateTypeNewCallbackQuery                         UpdateType = "updateNewCallbackQuery"
	UpdateTypeNewCallSignalingData                     UpdateType = "updateNewCallSignalingData"
	UpdateTypeNewChat                                  UpdateType = "updateNewChat"
	UpdateTypeNewChatJoinRequest                       UpdateType = "updateNewChatJoinRequest"
	UpdateTypeNewChosenInlineResult                    UpdateType = "updateNewChosenInlineResult"
	UpdateTypeNewCustomEvent                           UpdateType = "updateNewCustomEvent"
	UpdateTypeNewCustomQuery                           UpdateType = "updateNewCustomQuery"
	UpdateTypeNewGroupCallMessage                      UpdateType = "updateNewGroupCallMessage"
	UpdateTypeNewGroupCallPaidReaction                 UpdateType = "updateNewGroupCallPaidReaction"
	UpdateTypeNewGuestQuery                            UpdateType = "updateNewGuestQuery"
	UpdateTypeNewInlineCallbackQuery                   UpdateType = "updateNewInlineCallbackQuery"
	UpdateTypeNewInlineQuery                           UpdateType = "updateNewInlineQuery"
	UpdateTypeNewMessage                               UpdateType = "updateNewMessage"
	UpdateTypeNewOauthRequest                          UpdateType = "updateNewOauthRequest"
	UpdateTypeNewPreCheckoutQuery                      UpdateType = "updateNewPreCheckoutQuery"
	UpdateTypeNewShippingQuery                         UpdateType = "updateNewShippingQuery"
	UpdateTypeNotification                             UpdateType = "updateNotification"
	UpdateTypeNotificationGroup                        UpdateType = "updateNotificationGroup"
	UpdateTypeOption                                   UpdateType = "updateOption"
	UpdateTypeOwnedStarCount                           UpdateType = "updateOwnedStarCount"
	UpdateTypeOwnedTonCount                            UpdateType = "updateOwnedTonCount"
	UpdateTypePaidMediaPurchased                       UpdateType = "updatePaidMediaPurchased"
	UpdateTypePendingTextMessage                       UpdateType = "updatePendingTextMessage"
	UpdateTypePoll                                     UpdateType = "updatePoll"
	UpdateTypePollAnswer                               UpdateType = "updatePollAnswer"
	UpdateTypeProfileAccentColors                      UpdateType = "updateProfileAccentColors"
	UpdateTypeQuickReplyShortcut                       UpdateType = "updateQuickReplyShortcut"
	UpdateTypeQuickReplyShortcutDeleted                UpdateType = "updateQuickReplyShortcutDeleted"
	UpdateTypeQuickReplyShortcutMessages               UpdateType = "updateQuickReplyShortcutMessages"
	UpdateTypeQuickReplyShortcuts                      UpdateType = "updateQuickReplyShortcuts"
	UpdateTypeReactionNotificationSettings             UpdateType = "updateReactionNotificationSettings"
	UpdateTypeRecentStickers                           UpdateType = "updateRecentStickers"
	UpdateTypeSavedAnimations                          UpdateType = "updateSavedAnimations"
	UpdateTypeSavedMessagesTags                        UpdateType = "updateSavedMessagesTags"
	UpdateTypeSavedMessagesTopic                       UpdateType = "updateSavedMessagesTopic"
	UpdateTypeSavedMessagesTopicCount                  UpdateType = "updateSavedMessagesTopicCount"
	UpdateTypeSavedNotificationSounds                  UpdateType = "updateSavedNotificationSounds"
	UpdateTypeScopeNotificationSettings                UpdateType = "updateScopeNotificationSettings"
	UpdateTypeSecretChat                               UpdateType = "updateSecretChat"
	UpdateTypeServiceNotification                      UpdateType = "updateServiceNotification"
	UpdateTypeSpeechRecognitionTrial                   UpdateType = "updateSpeechRecognitionTrial"
	UpdateTypeSpeedLimitNotification                   UpdateType = "updateSpeedLimitNotification"
	UpdateTypeStakeDiceState                           UpdateType = "updateStakeDiceState"
	UpdateTypeStarRevenueStatus                        UpdateType = "updateStarRevenueStatus"
	UpdateTypeStickerSet                               UpdateType = "updateStickerSet"
	UpdateTypeStory                                    UpdateType = "updateStory"
	UpdateTypeStoryDeleted                             UpdateType = "updateStoryDeleted"
	UpdateTypeStoryListChatCount                       UpdateType = "updateStoryListChatCount"
	UpdateTypeStoryPostFailed                          UpdateType = "updateStoryPostFailed"
	UpdateTypeStoryPostSucceeded                       UpdateType = "updateStoryPostSucceeded"
	UpdateTypeStoryStealthMode                         UpdateType = "updateStoryStealthMode"
	UpdateTypeSuggestedActions                         UpdateType = "updateSuggestedActions"
	UpdateTypeSupergroup                               UpdateType = "updateSupergroup"
	UpdateTypeSupergroupFullInfo                       UpdateType = "updateSupergroupFullInfo"
	UpdateTypeTermsOfService                           UpdateType = "updateTermsOfService"
	UpdateTypeTextCompositionStyles                    UpdateType = "updateTextCompositionStyles"
	UpdateTypeTonRevenueStatus                         UpdateType = "updateTonRevenueStatus"
	UpdateTypeTopicMessageCount                        UpdateType = "updateTopicMessageCount"
	UpdateTypeTrendingStickerSets                      UpdateType = "updateTrendingStickerSets"
	UpdateTypeTrustedMiniAppBots                       UpdateType = "updateTrustedMiniAppBots"
	UpdateTypeUnconfirmedSession                       UpdateType = "updateUnconfirmedSession"
	UpdateTypeUnreadChatCount                          UpdateType = "updateUnreadChatCount"
	UpdateTypeUnreadMessageCount                       UpdateType = "updateUnreadMessageCount"
	UpdateTypeUser                                     UpdateType = "updateUser"
	UpdateTypeUserFullInfo                             UpdateType = "updateUserFullInfo"
	UpdateTypeUserPrivacySettingRules                  UpdateType = "updateUserPrivacySettingRules"
	UpdateTypeUserStatus                               UpdateType = "updateUserStatus"
	UpdateTypeVideoPublished                           UpdateType = "updateVideoPublished"
	UpdateTypeWebAppMessageSent                        UpdateType = "updateWebAppMessageSent"
)

// AddAccentColorsHandler registers a handler for UpdateAccentColors updates.
func (c *Client) AddAccentColorsHandler(hn HandlerFunc[UpdateAccentColors], f ...Filter) Handle {
	h := &handle[UpdateAccentColors]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeAccentColors,
	}

	c.addHandler(UpdateTypeAccentColors, h)

	return h
}

// AddActiveEmojiReactionsHandler registers a handler for UpdateActiveEmojiReactions updates.
func (c *Client) AddActiveEmojiReactionsHandler(hn HandlerFunc[UpdateActiveEmojiReactions], f ...Filter) Handle {
	h := &handle[UpdateActiveEmojiReactions]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeActiveEmojiReactions,
	}

	c.addHandler(UpdateTypeActiveEmojiReactions, h)

	return h
}

// AddActiveGiftAuctionsHandler registers a handler for UpdateActiveGiftAuctions updates.
func (c *Client) AddActiveGiftAuctionsHandler(hn HandlerFunc[UpdateActiveGiftAuctions], f ...Filter) Handle {
	h := &handle[UpdateActiveGiftAuctions]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeActiveGiftAuctions,
	}

	c.addHandler(UpdateTypeActiveGiftAuctions, h)

	return h
}

// AddActiveLiveLocationMessagesHandler registers a handler for UpdateActiveLiveLocationMessages updates.
func (c *Client) AddActiveLiveLocationMessagesHandler(hn HandlerFunc[UpdateActiveLiveLocationMessages], f ...Filter) Handle {
	h := &handle[UpdateActiveLiveLocationMessages]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeActiveLiveLocationMessages,
	}

	c.addHandler(UpdateTypeActiveLiveLocationMessages, h)

	return h
}

// AddActiveNotificationsHandler registers a handler for UpdateActiveNotifications updates.
func (c *Client) AddActiveNotificationsHandler(hn HandlerFunc[UpdateActiveNotifications], f ...Filter) Handle {
	h := &handle[UpdateActiveNotifications]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeActiveNotifications,
	}

	c.addHandler(UpdateTypeActiveNotifications, h)

	return h
}

// AddAgeVerificationParametersHandler registers a handler for UpdateAgeVerificationParameters updates.
func (c *Client) AddAgeVerificationParametersHandler(hn HandlerFunc[UpdateAgeVerificationParameters], f ...Filter) Handle {
	h := &handle[UpdateAgeVerificationParameters]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeAgeVerificationParameters,
	}

	c.addHandler(UpdateTypeAgeVerificationParameters, h)

	return h
}

// AddAnimatedEmojiMessageClickedHandler registers a handler for UpdateAnimatedEmojiMessageClicked updates.
func (c *Client) AddAnimatedEmojiMessageClickedHandler(hn HandlerFunc[UpdateAnimatedEmojiMessageClicked], f ...Filter) Handle {
	h := &handle[UpdateAnimatedEmojiMessageClicked]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeAnimatedEmojiMessageClicked,
	}

	c.addHandler(UpdateTypeAnimatedEmojiMessageClicked, h)

	return h
}

// AddAnimationSearchParametersHandler registers a handler for UpdateAnimationSearchParameters updates.
func (c *Client) AddAnimationSearchParametersHandler(hn HandlerFunc[UpdateAnimationSearchParameters], f ...Filter) Handle {
	h := &handle[UpdateAnimationSearchParameters]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeAnimationSearchParameters,
	}

	c.addHandler(UpdateTypeAnimationSearchParameters, h)

	return h
}

// AddApplicationRecaptchaVerificationRequiredHandler registers a handler for UpdateApplicationRecaptchaVerificationRequired updates.
func (c *Client) AddApplicationRecaptchaVerificationRequiredHandler(hn HandlerFunc[UpdateApplicationRecaptchaVerificationRequired], f ...Filter) Handle {
	h := &handle[UpdateApplicationRecaptchaVerificationRequired]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeApplicationRecaptchaVerificationRequired,
	}

	c.addHandler(UpdateTypeApplicationRecaptchaVerificationRequired, h)

	return h
}

// AddApplicationVerificationRequiredHandler registers a handler for UpdateApplicationVerificationRequired updates.
func (c *Client) AddApplicationVerificationRequiredHandler(hn HandlerFunc[UpdateApplicationVerificationRequired], f ...Filter) Handle {
	h := &handle[UpdateApplicationVerificationRequired]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeApplicationVerificationRequired,
	}

	c.addHandler(UpdateTypeApplicationVerificationRequired, h)

	return h
}

// AddAttachmentMenuBotsHandler registers a handler for UpdateAttachmentMenuBots updates.
func (c *Client) AddAttachmentMenuBotsHandler(hn HandlerFunc[UpdateAttachmentMenuBots], f ...Filter) Handle {
	h := &handle[UpdateAttachmentMenuBots]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeAttachmentMenuBots,
	}

	c.addHandler(UpdateTypeAttachmentMenuBots, h)

	return h
}

// AddAuthorizationStateHandler registers a handler for UpdateAuthorizationState updates.
func (c *Client) AddAuthorizationStateHandler(hn HandlerFunc[UpdateAuthorizationState], f ...Filter) Handle {
	h := &handle[UpdateAuthorizationState]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeAuthorizationState,
	}

	c.addHandler(UpdateTypeAuthorizationState, h)

	return h
}

// AddAutosaveSettingsHandler registers a handler for UpdateAutosaveSettings updates.
func (c *Client) AddAutosaveSettingsHandler(hn HandlerFunc[UpdateAutosaveSettings], f ...Filter) Handle {
	h := &handle[UpdateAutosaveSettings]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeAutosaveSettings,
	}

	c.addHandler(UpdateTypeAutosaveSettings, h)

	return h
}

// AddAvailableMessageEffectsHandler registers a handler for UpdateAvailableMessageEffects updates.
func (c *Client) AddAvailableMessageEffectsHandler(hn HandlerFunc[UpdateAvailableMessageEffects], f ...Filter) Handle {
	h := &handle[UpdateAvailableMessageEffects]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeAvailableMessageEffects,
	}

	c.addHandler(UpdateTypeAvailableMessageEffects, h)

	return h
}

// AddBasicGroupHandler registers a handler for UpdateBasicGroup updates.
func (c *Client) AddBasicGroupHandler(hn HandlerFunc[UpdateBasicGroup], f ...Filter) Handle {
	h := &handle[UpdateBasicGroup]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeBasicGroup,
	}

	c.addHandler(UpdateTypeBasicGroup, h)

	return h
}

// AddBasicGroupFullInfoHandler registers a handler for UpdateBasicGroupFullInfo updates.
func (c *Client) AddBasicGroupFullInfoHandler(hn HandlerFunc[UpdateBasicGroupFullInfo], f ...Filter) Handle {
	h := &handle[UpdateBasicGroupFullInfo]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeBasicGroupFullInfo,
	}

	c.addHandler(UpdateTypeBasicGroupFullInfo, h)

	return h
}

// AddBusinessConnectionHandler registers a handler for UpdateBusinessConnection updates.
func (c *Client) AddBusinessConnectionHandler(hn HandlerFunc[UpdateBusinessConnection], f ...Filter) Handle {
	h := &handle[UpdateBusinessConnection]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeBusinessConnection,
	}

	c.addHandler(UpdateTypeBusinessConnection, h)

	return h
}

// AddBusinessMessageEditedHandler registers a handler for UpdateBusinessMessageEdited updates.
func (c *Client) AddBusinessMessageEditedHandler(hn HandlerFunc[UpdateBusinessMessageEdited], f ...Filter) Handle {
	h := &handle[UpdateBusinessMessageEdited]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeBusinessMessageEdited,
	}

	c.addHandler(UpdateTypeBusinessMessageEdited, h)

	return h
}

// AddBusinessMessagesDeletedHandler registers a handler for UpdateBusinessMessagesDeleted updates.
func (c *Client) AddBusinessMessagesDeletedHandler(hn HandlerFunc[UpdateBusinessMessagesDeleted], f ...Filter) Handle {
	h := &handle[UpdateBusinessMessagesDeleted]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeBusinessMessagesDeleted,
	}

	c.addHandler(UpdateTypeBusinessMessagesDeleted, h)

	return h
}

// AddCallHandler registers a handler for UpdateCall updates.
func (c *Client) AddCallHandler(hn HandlerFunc[UpdateCall], f ...Filter) Handle {
	h := &handle[UpdateCall]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeCall,
	}

	c.addHandler(UpdateTypeCall, h)

	return h
}

// AddChatAccentColorsHandler registers a handler for UpdateChatAccentColors updates.
func (c *Client) AddChatAccentColorsHandler(hn HandlerFunc[UpdateChatAccentColors], f ...Filter) Handle {
	h := &handle[UpdateChatAccentColors]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatAccentColors,
	}

	c.addHandler(UpdateTypeChatAccentColors, h)

	return h
}

// AddChatActionHandler registers a handler for UpdateChatAction updates.
func (c *Client) AddChatActionHandler(hn HandlerFunc[UpdateChatAction], f ...Filter) Handle {
	h := &handle[UpdateChatAction]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatAction,
	}

	c.addHandler(UpdateTypeChatAction, h)

	return h
}

// AddChatActionBarHandler registers a handler for UpdateChatActionBar updates.
func (c *Client) AddChatActionBarHandler(hn HandlerFunc[UpdateChatActionBar], f ...Filter) Handle {
	h := &handle[UpdateChatActionBar]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatActionBar,
	}

	c.addHandler(UpdateTypeChatActionBar, h)

	return h
}

// AddChatActiveStoriesHandler registers a handler for UpdateChatActiveStories updates.
func (c *Client) AddChatActiveStoriesHandler(hn HandlerFunc[UpdateChatActiveStories], f ...Filter) Handle {
	h := &handle[UpdateChatActiveStories]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatActiveStories,
	}

	c.addHandler(UpdateTypeChatActiveStories, h)

	return h
}

// AddChatAddedToListHandler registers a handler for UpdateChatAddedToList updates.
func (c *Client) AddChatAddedToListHandler(hn HandlerFunc[UpdateChatAddedToList], f ...Filter) Handle {
	h := &handle[UpdateChatAddedToList]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatAddedToList,
	}

	c.addHandler(UpdateTypeChatAddedToList, h)

	return h
}

// AddChatAvailableReactionsHandler registers a handler for UpdateChatAvailableReactions updates.
func (c *Client) AddChatAvailableReactionsHandler(hn HandlerFunc[UpdateChatAvailableReactions], f ...Filter) Handle {
	h := &handle[UpdateChatAvailableReactions]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatAvailableReactions,
	}

	c.addHandler(UpdateTypeChatAvailableReactions, h)

	return h
}

// AddChatBackgroundHandler registers a handler for UpdateChatBackground updates.
func (c *Client) AddChatBackgroundHandler(hn HandlerFunc[UpdateChatBackground], f ...Filter) Handle {
	h := &handle[UpdateChatBackground]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatBackground,
	}

	c.addHandler(UpdateTypeChatBackground, h)

	return h
}

// AddChatBlockListHandler registers a handler for UpdateChatBlockList updates.
func (c *Client) AddChatBlockListHandler(hn HandlerFunc[UpdateChatBlockList], f ...Filter) Handle {
	h := &handle[UpdateChatBlockList]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatBlockList,
	}

	c.addHandler(UpdateTypeChatBlockList, h)

	return h
}

// AddChatBoostHandler registers a handler for UpdateChatBoost updates.
func (c *Client) AddChatBoostHandler(hn HandlerFunc[UpdateChatBoost], f ...Filter) Handle {
	h := &handle[UpdateChatBoost]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatBoost,
	}

	c.addHandler(UpdateTypeChatBoost, h)

	return h
}

// AddChatBusinessBotManageBarHandler registers a handler for UpdateChatBusinessBotManageBar updates.
func (c *Client) AddChatBusinessBotManageBarHandler(hn HandlerFunc[UpdateChatBusinessBotManageBar], f ...Filter) Handle {
	h := &handle[UpdateChatBusinessBotManageBar]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatBusinessBotManageBar,
	}

	c.addHandler(UpdateTypeChatBusinessBotManageBar, h)

	return h
}

// AddChatDefaultDisableNotificationHandler registers a handler for UpdateChatDefaultDisableNotification updates.
func (c *Client) AddChatDefaultDisableNotificationHandler(hn HandlerFunc[UpdateChatDefaultDisableNotification], f ...Filter) Handle {
	h := &handle[UpdateChatDefaultDisableNotification]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatDefaultDisableNotification,
	}

	c.addHandler(UpdateTypeChatDefaultDisableNotification, h)

	return h
}

// AddChatDraftMessageHandler registers a handler for UpdateChatDraftMessage updates.
func (c *Client) AddChatDraftMessageHandler(hn HandlerFunc[UpdateChatDraftMessage], f ...Filter) Handle {
	h := &handle[UpdateChatDraftMessage]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatDraftMessage,
	}

	c.addHandler(UpdateTypeChatDraftMessage, h)

	return h
}

// AddChatEmojiStatusHandler registers a handler for UpdateChatEmojiStatus updates.
func (c *Client) AddChatEmojiStatusHandler(hn HandlerFunc[UpdateChatEmojiStatus], f ...Filter) Handle {
	h := &handle[UpdateChatEmojiStatus]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatEmojiStatus,
	}

	c.addHandler(UpdateTypeChatEmojiStatus, h)

	return h
}

// AddChatFoldersHandler registers a handler for UpdateChatFolders updates.
func (c *Client) AddChatFoldersHandler(hn HandlerFunc[UpdateChatFolders], f ...Filter) Handle {
	h := &handle[UpdateChatFolders]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatFolders,
	}

	c.addHandler(UpdateTypeChatFolders, h)

	return h
}

// AddChatHasProtectedContentHandler registers a handler for UpdateChatHasProtectedContent updates.
func (c *Client) AddChatHasProtectedContentHandler(hn HandlerFunc[UpdateChatHasProtectedContent], f ...Filter) Handle {
	h := &handle[UpdateChatHasProtectedContent]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatHasProtectedContent,
	}

	c.addHandler(UpdateTypeChatHasProtectedContent, h)

	return h
}

// AddChatHasScheduledMessagesHandler registers a handler for UpdateChatHasScheduledMessages updates.
func (c *Client) AddChatHasScheduledMessagesHandler(hn HandlerFunc[UpdateChatHasScheduledMessages], f ...Filter) Handle {
	h := &handle[UpdateChatHasScheduledMessages]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatHasScheduledMessages,
	}

	c.addHandler(UpdateTypeChatHasScheduledMessages, h)

	return h
}

// AddChatIsMarkedAsUnreadHandler registers a handler for UpdateChatIsMarkedAsUnread updates.
func (c *Client) AddChatIsMarkedAsUnreadHandler(hn HandlerFunc[UpdateChatIsMarkedAsUnread], f ...Filter) Handle {
	h := &handle[UpdateChatIsMarkedAsUnread]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatIsMarkedAsUnread,
	}

	c.addHandler(UpdateTypeChatIsMarkedAsUnread, h)

	return h
}

// AddChatIsTranslatableHandler registers a handler for UpdateChatIsTranslatable updates.
func (c *Client) AddChatIsTranslatableHandler(hn HandlerFunc[UpdateChatIsTranslatable], f ...Filter) Handle {
	h := &handle[UpdateChatIsTranslatable]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatIsTranslatable,
	}

	c.addHandler(UpdateTypeChatIsTranslatable, h)

	return h
}

// AddChatLastMessageHandler registers a handler for UpdateChatLastMessage updates.
func (c *Client) AddChatLastMessageHandler(hn HandlerFunc[UpdateChatLastMessage], f ...Filter) Handle {
	h := &handle[UpdateChatLastMessage]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatLastMessage,
	}

	c.addHandler(UpdateTypeChatLastMessage, h)

	return h
}

// AddChatMemberHandler registers a handler for UpdateChatMember updates.
func (c *Client) AddChatMemberHandler(hn HandlerFunc[UpdateChatMember], f ...Filter) Handle {
	h := &handle[UpdateChatMember]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatMember,
	}

	c.addHandler(UpdateTypeChatMember, h)

	return h
}

// AddChatMessageAutoDeleteTimeHandler registers a handler for UpdateChatMessageAutoDeleteTime updates.
func (c *Client) AddChatMessageAutoDeleteTimeHandler(hn HandlerFunc[UpdateChatMessageAutoDeleteTime], f ...Filter) Handle {
	h := &handle[UpdateChatMessageAutoDeleteTime]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatMessageAutoDeleteTime,
	}

	c.addHandler(UpdateTypeChatMessageAutoDeleteTime, h)

	return h
}

// AddChatMessageSenderHandler registers a handler for UpdateChatMessageSender updates.
func (c *Client) AddChatMessageSenderHandler(hn HandlerFunc[UpdateChatMessageSender], f ...Filter) Handle {
	h := &handle[UpdateChatMessageSender]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatMessageSender,
	}

	c.addHandler(UpdateTypeChatMessageSender, h)

	return h
}

// AddChatNotificationSettingsHandler registers a handler for UpdateChatNotificationSettings updates.
func (c *Client) AddChatNotificationSettingsHandler(hn HandlerFunc[UpdateChatNotificationSettings], f ...Filter) Handle {
	h := &handle[UpdateChatNotificationSettings]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatNotificationSettings,
	}

	c.addHandler(UpdateTypeChatNotificationSettings, h)

	return h
}

// AddChatOnlineMemberCountHandler registers a handler for UpdateChatOnlineMemberCount updates.
func (c *Client) AddChatOnlineMemberCountHandler(hn HandlerFunc[UpdateChatOnlineMemberCount], f ...Filter) Handle {
	h := &handle[UpdateChatOnlineMemberCount]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatOnlineMemberCount,
	}

	c.addHandler(UpdateTypeChatOnlineMemberCount, h)

	return h
}

// AddChatPendingJoinRequestsHandler registers a handler for UpdateChatPendingJoinRequests updates.
func (c *Client) AddChatPendingJoinRequestsHandler(hn HandlerFunc[UpdateChatPendingJoinRequests], f ...Filter) Handle {
	h := &handle[UpdateChatPendingJoinRequests]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatPendingJoinRequests,
	}

	c.addHandler(UpdateTypeChatPendingJoinRequests, h)

	return h
}

// AddChatPermissionsHandler registers a handler for UpdateChatPermissions updates.
func (c *Client) AddChatPermissionsHandler(hn HandlerFunc[UpdateChatPermissions], f ...Filter) Handle {
	h := &handle[UpdateChatPermissions]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatPermissions,
	}

	c.addHandler(UpdateTypeChatPermissions, h)

	return h
}

// AddChatPhotoHandler registers a handler for UpdateChatPhoto updates.
func (c *Client) AddChatPhotoHandler(hn HandlerFunc[UpdateChatPhoto], f ...Filter) Handle {
	h := &handle[UpdateChatPhoto]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatPhoto,
	}

	c.addHandler(UpdateTypeChatPhoto, h)

	return h
}

// AddChatPositionHandler registers a handler for UpdateChatPosition updates.
func (c *Client) AddChatPositionHandler(hn HandlerFunc[UpdateChatPosition], f ...Filter) Handle {
	h := &handle[UpdateChatPosition]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatPosition,
	}

	c.addHandler(UpdateTypeChatPosition, h)

	return h
}

// AddChatReadInboxHandler registers a handler for UpdateChatReadInbox updates.
func (c *Client) AddChatReadInboxHandler(hn HandlerFunc[UpdateChatReadInbox], f ...Filter) Handle {
	h := &handle[UpdateChatReadInbox]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatReadInbox,
	}

	c.addHandler(UpdateTypeChatReadInbox, h)

	return h
}

// AddChatReadOutboxHandler registers a handler for UpdateChatReadOutbox updates.
func (c *Client) AddChatReadOutboxHandler(hn HandlerFunc[UpdateChatReadOutbox], f ...Filter) Handle {
	h := &handle[UpdateChatReadOutbox]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatReadOutbox,
	}

	c.addHandler(UpdateTypeChatReadOutbox, h)

	return h
}

// AddChatRemovedFromListHandler registers a handler for UpdateChatRemovedFromList updates.
func (c *Client) AddChatRemovedFromListHandler(hn HandlerFunc[UpdateChatRemovedFromList], f ...Filter) Handle {
	h := &handle[UpdateChatRemovedFromList]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatRemovedFromList,
	}

	c.addHandler(UpdateTypeChatRemovedFromList, h)

	return h
}

// AddChatReplyMarkupHandler registers a handler for UpdateChatReplyMarkup updates.
func (c *Client) AddChatReplyMarkupHandler(hn HandlerFunc[UpdateChatReplyMarkup], f ...Filter) Handle {
	h := &handle[UpdateChatReplyMarkup]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatReplyMarkup,
	}

	c.addHandler(UpdateTypeChatReplyMarkup, h)

	return h
}

// AddChatRevenueAmountHandler registers a handler for UpdateChatRevenueAmount updates.
func (c *Client) AddChatRevenueAmountHandler(hn HandlerFunc[UpdateChatRevenueAmount], f ...Filter) Handle {
	h := &handle[UpdateChatRevenueAmount]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatRevenueAmount,
	}

	c.addHandler(UpdateTypeChatRevenueAmount, h)

	return h
}

// AddChatThemeHandler registers a handler for UpdateChatTheme updates.
func (c *Client) AddChatThemeHandler(hn HandlerFunc[UpdateChatTheme], f ...Filter) Handle {
	h := &handle[UpdateChatTheme]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatTheme,
	}

	c.addHandler(UpdateTypeChatTheme, h)

	return h
}

// AddChatTitleHandler registers a handler for UpdateChatTitle updates.
func (c *Client) AddChatTitleHandler(hn HandlerFunc[UpdateChatTitle], f ...Filter) Handle {
	h := &handle[UpdateChatTitle]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatTitle,
	}

	c.addHandler(UpdateTypeChatTitle, h)

	return h
}

// AddChatUnreadMentionCountHandler registers a handler for UpdateChatUnreadMentionCount updates.
func (c *Client) AddChatUnreadMentionCountHandler(hn HandlerFunc[UpdateChatUnreadMentionCount], f ...Filter) Handle {
	h := &handle[UpdateChatUnreadMentionCount]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatUnreadMentionCount,
	}

	c.addHandler(UpdateTypeChatUnreadMentionCount, h)

	return h
}

// AddChatUnreadPollVoteCountHandler registers a handler for UpdateChatUnreadPollVoteCount updates.
func (c *Client) AddChatUnreadPollVoteCountHandler(hn HandlerFunc[UpdateChatUnreadPollVoteCount], f ...Filter) Handle {
	h := &handle[UpdateChatUnreadPollVoteCount]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatUnreadPollVoteCount,
	}

	c.addHandler(UpdateTypeChatUnreadPollVoteCount, h)

	return h
}

// AddChatUnreadReactionCountHandler registers a handler for UpdateChatUnreadReactionCount updates.
func (c *Client) AddChatUnreadReactionCountHandler(hn HandlerFunc[UpdateChatUnreadReactionCount], f ...Filter) Handle {
	h := &handle[UpdateChatUnreadReactionCount]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatUnreadReactionCount,
	}

	c.addHandler(UpdateTypeChatUnreadReactionCount, h)

	return h
}

// AddChatVideoChatHandler registers a handler for UpdateChatVideoChat updates.
func (c *Client) AddChatVideoChatHandler(hn HandlerFunc[UpdateChatVideoChat], f ...Filter) Handle {
	h := &handle[UpdateChatVideoChat]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatVideoChat,
	}

	c.addHandler(UpdateTypeChatVideoChat, h)

	return h
}

// AddChatViewAsTopicsHandler registers a handler for UpdateChatViewAsTopics updates.
func (c *Client) AddChatViewAsTopicsHandler(hn HandlerFunc[UpdateChatViewAsTopics], f ...Filter) Handle {
	h := &handle[UpdateChatViewAsTopics]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeChatViewAsTopics,
	}

	c.addHandler(UpdateTypeChatViewAsTopics, h)

	return h
}

// AddConnectionStateHandler registers a handler for UpdateConnectionState updates.
func (c *Client) AddConnectionStateHandler(hn HandlerFunc[UpdateConnectionState], f ...Filter) Handle {
	h := &handle[UpdateConnectionState]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeConnectionState,
	}

	c.addHandler(UpdateTypeConnectionState, h)

	return h
}

// AddContactCloseBirthdaysHandler registers a handler for UpdateContactCloseBirthdays updates.
func (c *Client) AddContactCloseBirthdaysHandler(hn HandlerFunc[UpdateContactCloseBirthdays], f ...Filter) Handle {
	h := &handle[UpdateContactCloseBirthdays]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeContactCloseBirthdays,
	}

	c.addHandler(UpdateTypeContactCloseBirthdays, h)

	return h
}

// AddDefaultBackgroundHandler registers a handler for UpdateDefaultBackground updates.
func (c *Client) AddDefaultBackgroundHandler(hn HandlerFunc[UpdateDefaultBackground], f ...Filter) Handle {
	h := &handle[UpdateDefaultBackground]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeDefaultBackground,
	}

	c.addHandler(UpdateTypeDefaultBackground, h)

	return h
}

// AddDefaultPaidReactionTypeHandler registers a handler for UpdateDefaultPaidReactionType updates.
func (c *Client) AddDefaultPaidReactionTypeHandler(hn HandlerFunc[UpdateDefaultPaidReactionType], f ...Filter) Handle {
	h := &handle[UpdateDefaultPaidReactionType]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeDefaultPaidReactionType,
	}

	c.addHandler(UpdateTypeDefaultPaidReactionType, h)

	return h
}

// AddDefaultReactionTypeHandler registers a handler for UpdateDefaultReactionType updates.
func (c *Client) AddDefaultReactionTypeHandler(hn HandlerFunc[UpdateDefaultReactionType], f ...Filter) Handle {
	h := &handle[UpdateDefaultReactionType]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeDefaultReactionType,
	}

	c.addHandler(UpdateTypeDefaultReactionType, h)

	return h
}

// AddDeleteMessagesHandler registers a handler for UpdateDeleteMessages updates.
func (c *Client) AddDeleteMessagesHandler(hn HandlerFunc[UpdateDeleteMessages], f ...Filter) Handle {
	h := &handle[UpdateDeleteMessages]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeDeleteMessages,
	}

	c.addHandler(UpdateTypeDeleteMessages, h)

	return h
}

// AddDiceEmojisHandler registers a handler for UpdateDiceEmojis updates.
func (c *Client) AddDiceEmojisHandler(hn HandlerFunc[UpdateDiceEmojis], f ...Filter) Handle {
	h := &handle[UpdateDiceEmojis]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeDiceEmojis,
	}

	c.addHandler(UpdateTypeDiceEmojis, h)

	return h
}

// AddDirectMessagesChatTopicHandler registers a handler for UpdateDirectMessagesChatTopic updates.
func (c *Client) AddDirectMessagesChatTopicHandler(hn HandlerFunc[UpdateDirectMessagesChatTopic], f ...Filter) Handle {
	h := &handle[UpdateDirectMessagesChatTopic]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeDirectMessagesChatTopic,
	}

	c.addHandler(UpdateTypeDirectMessagesChatTopic, h)

	return h
}

// AddEmojiChatThemesHandler registers a handler for UpdateEmojiChatThemes updates.
func (c *Client) AddEmojiChatThemesHandler(hn HandlerFunc[UpdateEmojiChatThemes], f ...Filter) Handle {
	h := &handle[UpdateEmojiChatThemes]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeEmojiChatThemes,
	}

	c.addHandler(UpdateTypeEmojiChatThemes, h)

	return h
}

// AddFavoriteStickersHandler registers a handler for UpdateFavoriteStickers updates.
func (c *Client) AddFavoriteStickersHandler(hn HandlerFunc[UpdateFavoriteStickers], f ...Filter) Handle {
	h := &handle[UpdateFavoriteStickers]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeFavoriteStickers,
	}

	c.addHandler(UpdateTypeFavoriteStickers, h)

	return h
}

// AddFileHandler registers a handler for UpdateFile updates.
func (c *Client) AddFileHandler(hn HandlerFunc[UpdateFile], f ...Filter) Handle {
	h := &handle[UpdateFile]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeFile,
	}

	c.addHandler(UpdateTypeFile, h)

	return h
}

// AddFileAddedToDownloadsHandler registers a handler for UpdateFileAddedToDownloads updates.
func (c *Client) AddFileAddedToDownloadsHandler(hn HandlerFunc[UpdateFileAddedToDownloads], f ...Filter) Handle {
	h := &handle[UpdateFileAddedToDownloads]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeFileAddedToDownloads,
	}

	c.addHandler(UpdateTypeFileAddedToDownloads, h)

	return h
}

// AddFileDownloadHandler registers a handler for UpdateFileDownload updates.
func (c *Client) AddFileDownloadHandler(hn HandlerFunc[UpdateFileDownload], f ...Filter) Handle {
	h := &handle[UpdateFileDownload]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeFileDownload,
	}

	c.addHandler(UpdateTypeFileDownload, h)

	return h
}

// AddFileDownloadsHandler registers a handler for UpdateFileDownloads updates.
func (c *Client) AddFileDownloadsHandler(hn HandlerFunc[UpdateFileDownloads], f ...Filter) Handle {
	h := &handle[UpdateFileDownloads]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeFileDownloads,
	}

	c.addHandler(UpdateTypeFileDownloads, h)

	return h
}

// AddFileGenerationStartHandler registers a handler for UpdateFileGenerationStart updates.
func (c *Client) AddFileGenerationStartHandler(hn HandlerFunc[UpdateFileGenerationStart], f ...Filter) Handle {
	h := &handle[UpdateFileGenerationStart]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeFileGenerationStart,
	}

	c.addHandler(UpdateTypeFileGenerationStart, h)

	return h
}

// AddFileGenerationStopHandler registers a handler for UpdateFileGenerationStop updates.
func (c *Client) AddFileGenerationStopHandler(hn HandlerFunc[UpdateFileGenerationStop], f ...Filter) Handle {
	h := &handle[UpdateFileGenerationStop]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeFileGenerationStop,
	}

	c.addHandler(UpdateTypeFileGenerationStop, h)

	return h
}

// AddFileRemovedFromDownloadsHandler registers a handler for UpdateFileRemovedFromDownloads updates.
func (c *Client) AddFileRemovedFromDownloadsHandler(hn HandlerFunc[UpdateFileRemovedFromDownloads], f ...Filter) Handle {
	h := &handle[UpdateFileRemovedFromDownloads]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeFileRemovedFromDownloads,
	}

	c.addHandler(UpdateTypeFileRemovedFromDownloads, h)

	return h
}

// AddForumTopicHandler registers a handler for UpdateForumTopic updates.
func (c *Client) AddForumTopicHandler(hn HandlerFunc[UpdateForumTopic], f ...Filter) Handle {
	h := &handle[UpdateForumTopic]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeForumTopic,
	}

	c.addHandler(UpdateTypeForumTopic, h)

	return h
}

// AddForumTopicInfoHandler registers a handler for UpdateForumTopicInfo updates.
func (c *Client) AddForumTopicInfoHandler(hn HandlerFunc[UpdateForumTopicInfo], f ...Filter) Handle {
	h := &handle[UpdateForumTopicInfo]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeForumTopicInfo,
	}

	c.addHandler(UpdateTypeForumTopicInfo, h)

	return h
}

// AddFreezeStateHandler registers a handler for UpdateFreezeState updates.
func (c *Client) AddFreezeStateHandler(hn HandlerFunc[UpdateFreezeState], f ...Filter) Handle {
	h := &handle[UpdateFreezeState]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeFreezeState,
	}

	c.addHandler(UpdateTypeFreezeState, h)

	return h
}

// AddGiftAuctionStateHandler registers a handler for UpdateGiftAuctionState updates.
func (c *Client) AddGiftAuctionStateHandler(hn HandlerFunc[UpdateGiftAuctionState], f ...Filter) Handle {
	h := &handle[UpdateGiftAuctionState]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeGiftAuctionState,
	}

	c.addHandler(UpdateTypeGiftAuctionState, h)

	return h
}

// AddGroupCallHandler registers a handler for UpdateGroupCall updates.
func (c *Client) AddGroupCallHandler(hn HandlerFunc[UpdateGroupCall], f ...Filter) Handle {
	h := &handle[UpdateGroupCall]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeGroupCall,
	}

	c.addHandler(UpdateTypeGroupCall, h)

	return h
}

// AddGroupCallMessageLevelsHandler registers a handler for UpdateGroupCallMessageLevels updates.
func (c *Client) AddGroupCallMessageLevelsHandler(hn HandlerFunc[UpdateGroupCallMessageLevels], f ...Filter) Handle {
	h := &handle[UpdateGroupCallMessageLevels]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeGroupCallMessageLevels,
	}

	c.addHandler(UpdateTypeGroupCallMessageLevels, h)

	return h
}

// AddGroupCallMessagesDeletedHandler registers a handler for UpdateGroupCallMessagesDeleted updates.
func (c *Client) AddGroupCallMessagesDeletedHandler(hn HandlerFunc[UpdateGroupCallMessagesDeleted], f ...Filter) Handle {
	h := &handle[UpdateGroupCallMessagesDeleted]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeGroupCallMessagesDeleted,
	}

	c.addHandler(UpdateTypeGroupCallMessagesDeleted, h)

	return h
}

// AddGroupCallMessageSendFailedHandler registers a handler for UpdateGroupCallMessageSendFailed updates.
func (c *Client) AddGroupCallMessageSendFailedHandler(hn HandlerFunc[UpdateGroupCallMessageSendFailed], f ...Filter) Handle {
	h := &handle[UpdateGroupCallMessageSendFailed]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeGroupCallMessageSendFailed,
	}

	c.addHandler(UpdateTypeGroupCallMessageSendFailed, h)

	return h
}

// AddGroupCallParticipantHandler registers a handler for UpdateGroupCallParticipant updates.
func (c *Client) AddGroupCallParticipantHandler(hn HandlerFunc[UpdateGroupCallParticipant], f ...Filter) Handle {
	h := &handle[UpdateGroupCallParticipant]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeGroupCallParticipant,
	}

	c.addHandler(UpdateTypeGroupCallParticipant, h)

	return h
}

// AddGroupCallParticipantsHandler registers a handler for UpdateGroupCallParticipants updates.
func (c *Client) AddGroupCallParticipantsHandler(hn HandlerFunc[UpdateGroupCallParticipants], f ...Filter) Handle {
	h := &handle[UpdateGroupCallParticipants]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeGroupCallParticipants,
	}

	c.addHandler(UpdateTypeGroupCallParticipants, h)

	return h
}

// AddGroupCallVerificationStateHandler registers a handler for UpdateGroupCallVerificationState updates.
func (c *Client) AddGroupCallVerificationStateHandler(hn HandlerFunc[UpdateGroupCallVerificationState], f ...Filter) Handle {
	h := &handle[UpdateGroupCallVerificationState]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeGroupCallVerificationState,
	}

	c.addHandler(UpdateTypeGroupCallVerificationState, h)

	return h
}

// AddHavePendingNotificationsHandler registers a handler for UpdateHavePendingNotifications updates.
func (c *Client) AddHavePendingNotificationsHandler(hn HandlerFunc[UpdateHavePendingNotifications], f ...Filter) Handle {
	h := &handle[UpdateHavePendingNotifications]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeHavePendingNotifications,
	}

	c.addHandler(UpdateTypeHavePendingNotifications, h)

	return h
}

// AddInstalledStickerSetsHandler registers a handler for UpdateInstalledStickerSets updates.
func (c *Client) AddInstalledStickerSetsHandler(hn HandlerFunc[UpdateInstalledStickerSets], f ...Filter) Handle {
	h := &handle[UpdateInstalledStickerSets]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeInstalledStickerSets,
	}

	c.addHandler(UpdateTypeInstalledStickerSets, h)

	return h
}

// AddLanguagePackStringsHandler registers a handler for UpdateLanguagePackStrings updates.
func (c *Client) AddLanguagePackStringsHandler(hn HandlerFunc[UpdateLanguagePackStrings], f ...Filter) Handle {
	h := &handle[UpdateLanguagePackStrings]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeLanguagePackStrings,
	}

	c.addHandler(UpdateTypeLanguagePackStrings, h)

	return h
}

// AddLiveStoryTopDonorsHandler registers a handler for UpdateLiveStoryTopDonors updates.
func (c *Client) AddLiveStoryTopDonorsHandler(hn HandlerFunc[UpdateLiveStoryTopDonors], f ...Filter) Handle {
	h := &handle[UpdateLiveStoryTopDonors]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeLiveStoryTopDonors,
	}

	c.addHandler(UpdateTypeLiveStoryTopDonors, h)

	return h
}

// AddManagedBotHandler registers a handler for UpdateManagedBot updates.
func (c *Client) AddManagedBotHandler(hn HandlerFunc[UpdateManagedBot], f ...Filter) Handle {
	h := &handle[UpdateManagedBot]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeManagedBot,
	}

	c.addHandler(UpdateTypeManagedBot, h)

	return h
}

// AddMessageContainsUnreadPollVotesHandler registers a handler for UpdateMessageContainsUnreadPollVotes updates.
func (c *Client) AddMessageContainsUnreadPollVotesHandler(hn HandlerFunc[UpdateMessageContainsUnreadPollVotes], f ...Filter) Handle {
	h := &handle[UpdateMessageContainsUnreadPollVotes]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageContainsUnreadPollVotes,
	}

	c.addHandler(UpdateTypeMessageContainsUnreadPollVotes, h)

	return h
}

// AddMessageContentHandler registers a handler for UpdateMessageContent updates.
func (c *Client) AddMessageContentHandler(hn HandlerFunc[UpdateMessageContent], f ...Filter) Handle {
	h := &handle[UpdateMessageContent]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageContent,
	}

	c.addHandler(UpdateTypeMessageContent, h)

	return h
}

// AddMessageContentOpenedHandler registers a handler for UpdateMessageContentOpened updates.
func (c *Client) AddMessageContentOpenedHandler(hn HandlerFunc[UpdateMessageContentOpened], f ...Filter) Handle {
	h := &handle[UpdateMessageContentOpened]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageContentOpened,
	}

	c.addHandler(UpdateTypeMessageContentOpened, h)

	return h
}

// AddMessageEditedHandler registers a handler for UpdateMessageEdited updates.
func (c *Client) AddMessageEditedHandler(hn HandlerFunc[UpdateMessageEdited], f ...Filter) Handle {
	h := &handle[UpdateMessageEdited]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageEdited,
	}

	c.addHandler(UpdateTypeMessageEdited, h)

	return h
}

// AddMessageFactCheckHandler registers a handler for UpdateMessageFactCheck updates.
func (c *Client) AddMessageFactCheckHandler(hn HandlerFunc[UpdateMessageFactCheck], f ...Filter) Handle {
	h := &handle[UpdateMessageFactCheck]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageFactCheck,
	}

	c.addHandler(UpdateTypeMessageFactCheck, h)

	return h
}

// AddMessageInteractionInfoHandler registers a handler for UpdateMessageInteractionInfo updates.
func (c *Client) AddMessageInteractionInfoHandler(hn HandlerFunc[UpdateMessageInteractionInfo], f ...Filter) Handle {
	h := &handle[UpdateMessageInteractionInfo]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageInteractionInfo,
	}

	c.addHandler(UpdateTypeMessageInteractionInfo, h)

	return h
}

// AddMessageIsPinnedHandler registers a handler for UpdateMessageIsPinned updates.
func (c *Client) AddMessageIsPinnedHandler(hn HandlerFunc[UpdateMessageIsPinned], f ...Filter) Handle {
	h := &handle[UpdateMessageIsPinned]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageIsPinned,
	}

	c.addHandler(UpdateTypeMessageIsPinned, h)

	return h
}

// AddMessageLiveLocationViewedHandler registers a handler for UpdateMessageLiveLocationViewed updates.
func (c *Client) AddMessageLiveLocationViewedHandler(hn HandlerFunc[UpdateMessageLiveLocationViewed], f ...Filter) Handle {
	h := &handle[UpdateMessageLiveLocationViewed]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageLiveLocationViewed,
	}

	c.addHandler(UpdateTypeMessageLiveLocationViewed, h)

	return h
}

// AddMessageMentionReadHandler registers a handler for UpdateMessageMentionRead updates.
func (c *Client) AddMessageMentionReadHandler(hn HandlerFunc[UpdateMessageMentionRead], f ...Filter) Handle {
	h := &handle[UpdateMessageMentionRead]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageMentionRead,
	}

	c.addHandler(UpdateTypeMessageMentionRead, h)

	return h
}

// AddMessageReactionHandler registers a handler for UpdateMessageReaction updates.
func (c *Client) AddMessageReactionHandler(hn HandlerFunc[UpdateMessageReaction], f ...Filter) Handle {
	h := &handle[UpdateMessageReaction]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageReaction,
	}

	c.addHandler(UpdateTypeMessageReaction, h)

	return h
}

// AddMessageReactionsHandler registers a handler for UpdateMessageReactions updates.
func (c *Client) AddMessageReactionsHandler(hn HandlerFunc[UpdateMessageReactions], f ...Filter) Handle {
	h := &handle[UpdateMessageReactions]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageReactions,
	}

	c.addHandler(UpdateTypeMessageReactions, h)

	return h
}

// AddMessageSendAcknowledgedHandler registers a handler for UpdateMessageSendAcknowledged updates.
func (c *Client) AddMessageSendAcknowledgedHandler(hn HandlerFunc[UpdateMessageSendAcknowledged], f ...Filter) Handle {
	h := &handle[UpdateMessageSendAcknowledged]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageSendAcknowledged,
	}

	c.addHandler(UpdateTypeMessageSendAcknowledged, h)

	return h
}

// AddMessageSendFailedHandler registers a handler for UpdateMessageSendFailed updates.
func (c *Client) AddMessageSendFailedHandler(hn HandlerFunc[UpdateMessageSendFailed], f ...Filter) Handle {
	h := &handle[UpdateMessageSendFailed]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageSendFailed,
	}

	c.addHandler(UpdateTypeMessageSendFailed, h)

	return h
}

// AddMessageSendSucceededHandler registers a handler for UpdateMessageSendSucceeded updates.
func (c *Client) AddMessageSendSucceededHandler(hn HandlerFunc[UpdateMessageSendSucceeded], f ...Filter) Handle {
	h := &handle[UpdateMessageSendSucceeded]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageSendSucceeded,
	}

	c.addHandler(UpdateTypeMessageSendSucceeded, h)

	return h
}

// AddMessageSuggestedPostInfoHandler registers a handler for UpdateMessageSuggestedPostInfo updates.
func (c *Client) AddMessageSuggestedPostInfoHandler(hn HandlerFunc[UpdateMessageSuggestedPostInfo], f ...Filter) Handle {
	h := &handle[UpdateMessageSuggestedPostInfo]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageSuggestedPostInfo,
	}

	c.addHandler(UpdateTypeMessageSuggestedPostInfo, h)

	return h
}

// AddMessageUnreadReactionsHandler registers a handler for UpdateMessageUnreadReactions updates.
func (c *Client) AddMessageUnreadReactionsHandler(hn HandlerFunc[UpdateMessageUnreadReactions], f ...Filter) Handle {
	h := &handle[UpdateMessageUnreadReactions]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeMessageUnreadReactions,
	}

	c.addHandler(UpdateTypeMessageUnreadReactions, h)

	return h
}

// AddNewBusinessCallbackQueryHandler registers a handler for UpdateNewBusinessCallbackQuery updates.
func (c *Client) AddNewBusinessCallbackQueryHandler(hn HandlerFunc[UpdateNewBusinessCallbackQuery], f ...Filter) Handle {
	h := &handle[UpdateNewBusinessCallbackQuery]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewBusinessCallbackQuery,
	}

	c.addHandler(UpdateTypeNewBusinessCallbackQuery, h)

	return h
}

// AddNewBusinessMessageHandler registers a handler for UpdateNewBusinessMessage updates.
func (c *Client) AddNewBusinessMessageHandler(hn HandlerFunc[UpdateNewBusinessMessage], f ...Filter) Handle {
	h := &handle[UpdateNewBusinessMessage]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewBusinessMessage,
	}

	c.addHandler(UpdateTypeNewBusinessMessage, h)

	return h
}

// AddNewCallbackQueryHandler registers a handler for UpdateNewCallbackQuery updates.
func (c *Client) AddNewCallbackQueryHandler(hn HandlerFunc[UpdateNewCallbackQuery], f ...Filter) Handle {
	h := &handle[UpdateNewCallbackQuery]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewCallbackQuery,
	}

	c.addHandler(UpdateTypeNewCallbackQuery, h)

	return h
}

// AddNewCallSignalingDataHandler registers a handler for UpdateNewCallSignalingData updates.
func (c *Client) AddNewCallSignalingDataHandler(hn HandlerFunc[UpdateNewCallSignalingData], f ...Filter) Handle {
	h := &handle[UpdateNewCallSignalingData]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewCallSignalingData,
	}

	c.addHandler(UpdateTypeNewCallSignalingData, h)

	return h
}

// AddNewChatHandler registers a handler for UpdateNewChat updates.
func (c *Client) AddNewChatHandler(hn HandlerFunc[UpdateNewChat], f ...Filter) Handle {
	h := &handle[UpdateNewChat]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewChat,
	}

	c.addHandler(UpdateTypeNewChat, h)

	return h
}

// AddNewChatJoinRequestHandler registers a handler for UpdateNewChatJoinRequest updates.
func (c *Client) AddNewChatJoinRequestHandler(hn HandlerFunc[UpdateNewChatJoinRequest], f ...Filter) Handle {
	h := &handle[UpdateNewChatJoinRequest]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewChatJoinRequest,
	}

	c.addHandler(UpdateTypeNewChatJoinRequest, h)

	return h
}

// AddNewChosenInlineResultHandler registers a handler for UpdateNewChosenInlineResult updates.
func (c *Client) AddNewChosenInlineResultHandler(hn HandlerFunc[UpdateNewChosenInlineResult], f ...Filter) Handle {
	h := &handle[UpdateNewChosenInlineResult]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewChosenInlineResult,
	}

	c.addHandler(UpdateTypeNewChosenInlineResult, h)

	return h
}

// AddNewCustomEventHandler registers a handler for UpdateNewCustomEvent updates.
func (c *Client) AddNewCustomEventHandler(hn HandlerFunc[UpdateNewCustomEvent], f ...Filter) Handle {
	h := &handle[UpdateNewCustomEvent]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewCustomEvent,
	}

	c.addHandler(UpdateTypeNewCustomEvent, h)

	return h
}

// AddNewCustomQueryHandler registers a handler for UpdateNewCustomQuery updates.
func (c *Client) AddNewCustomQueryHandler(hn HandlerFunc[UpdateNewCustomQuery], f ...Filter) Handle {
	h := &handle[UpdateNewCustomQuery]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewCustomQuery,
	}

	c.addHandler(UpdateTypeNewCustomQuery, h)

	return h
}

// AddNewGroupCallMessageHandler registers a handler for UpdateNewGroupCallMessage updates.
func (c *Client) AddNewGroupCallMessageHandler(hn HandlerFunc[UpdateNewGroupCallMessage], f ...Filter) Handle {
	h := &handle[UpdateNewGroupCallMessage]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewGroupCallMessage,
	}

	c.addHandler(UpdateTypeNewGroupCallMessage, h)

	return h
}

// AddNewGroupCallPaidReactionHandler registers a handler for UpdateNewGroupCallPaidReaction updates.
func (c *Client) AddNewGroupCallPaidReactionHandler(hn HandlerFunc[UpdateNewGroupCallPaidReaction], f ...Filter) Handle {
	h := &handle[UpdateNewGroupCallPaidReaction]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewGroupCallPaidReaction,
	}

	c.addHandler(UpdateTypeNewGroupCallPaidReaction, h)

	return h
}

// AddNewGuestQueryHandler registers a handler for UpdateNewGuestQuery updates.
func (c *Client) AddNewGuestQueryHandler(hn HandlerFunc[UpdateNewGuestQuery], f ...Filter) Handle {
	h := &handle[UpdateNewGuestQuery]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewGuestQuery,
	}

	c.addHandler(UpdateTypeNewGuestQuery, h)

	return h
}

// AddNewInlineCallbackQueryHandler registers a handler for UpdateNewInlineCallbackQuery updates.
func (c *Client) AddNewInlineCallbackQueryHandler(hn HandlerFunc[UpdateNewInlineCallbackQuery], f ...Filter) Handle {
	h := &handle[UpdateNewInlineCallbackQuery]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewInlineCallbackQuery,
	}

	c.addHandler(UpdateTypeNewInlineCallbackQuery, h)

	return h
}

// AddNewInlineQueryHandler registers a handler for UpdateNewInlineQuery updates.
func (c *Client) AddNewInlineQueryHandler(hn HandlerFunc[UpdateNewInlineQuery], f ...Filter) Handle {
	h := &handle[UpdateNewInlineQuery]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewInlineQuery,
	}

	c.addHandler(UpdateTypeNewInlineQuery, h)

	return h
}

// AddNewMessageHandler registers a handler for UpdateNewMessage updates.
func (c *Client) AddNewMessageHandler(hn HandlerFunc[UpdateNewMessage], f ...Filter) Handle {
	h := &handle[UpdateNewMessage]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewMessage,
	}

	h.applyDefaultFilters()
	c.addHandler(UpdateTypeNewMessage, h)

	return h
}

// AddNewOauthRequestHandler registers a handler for UpdateNewOauthRequest updates.
func (c *Client) AddNewOauthRequestHandler(hn HandlerFunc[UpdateNewOauthRequest], f ...Filter) Handle {
	h := &handle[UpdateNewOauthRequest]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewOauthRequest,
	}

	c.addHandler(UpdateTypeNewOauthRequest, h)

	return h
}

// AddNewPreCheckoutQueryHandler registers a handler for UpdateNewPreCheckoutQuery updates.
func (c *Client) AddNewPreCheckoutQueryHandler(hn HandlerFunc[UpdateNewPreCheckoutQuery], f ...Filter) Handle {
	h := &handle[UpdateNewPreCheckoutQuery]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewPreCheckoutQuery,
	}

	c.addHandler(UpdateTypeNewPreCheckoutQuery, h)

	return h
}

// AddNewShippingQueryHandler registers a handler for UpdateNewShippingQuery updates.
func (c *Client) AddNewShippingQueryHandler(hn HandlerFunc[UpdateNewShippingQuery], f ...Filter) Handle {
	h := &handle[UpdateNewShippingQuery]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNewShippingQuery,
	}

	c.addHandler(UpdateTypeNewShippingQuery, h)

	return h
}

// AddNotificationHandler registers a handler for UpdateNotification updates.
func (c *Client) AddNotificationHandler(hn HandlerFunc[UpdateNotification], f ...Filter) Handle {
	h := &handle[UpdateNotification]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNotification,
	}

	c.addHandler(UpdateTypeNotification, h)

	return h
}

// AddNotificationGroupHandler registers a handler for UpdateNotificationGroup updates.
func (c *Client) AddNotificationGroupHandler(hn HandlerFunc[UpdateNotificationGroup], f ...Filter) Handle {
	h := &handle[UpdateNotificationGroup]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeNotificationGroup,
	}

	c.addHandler(UpdateTypeNotificationGroup, h)

	return h
}

// AddOptionHandler registers a handler for UpdateOption updates.
func (c *Client) AddOptionHandler(hn HandlerFunc[UpdateOption], f ...Filter) Handle {
	h := &handle[UpdateOption]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeOption,
	}

	c.addHandler(UpdateTypeOption, h)

	return h
}

// AddOwnedStarCountHandler registers a handler for UpdateOwnedStarCount updates.
func (c *Client) AddOwnedStarCountHandler(hn HandlerFunc[UpdateOwnedStarCount], f ...Filter) Handle {
	h := &handle[UpdateOwnedStarCount]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeOwnedStarCount,
	}

	c.addHandler(UpdateTypeOwnedStarCount, h)

	return h
}

// AddOwnedTonCountHandler registers a handler for UpdateOwnedTonCount updates.
func (c *Client) AddOwnedTonCountHandler(hn HandlerFunc[UpdateOwnedTonCount], f ...Filter) Handle {
	h := &handle[UpdateOwnedTonCount]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeOwnedTonCount,
	}

	c.addHandler(UpdateTypeOwnedTonCount, h)

	return h
}

// AddPaidMediaPurchasedHandler registers a handler for UpdatePaidMediaPurchased updates.
func (c *Client) AddPaidMediaPurchasedHandler(hn HandlerFunc[UpdatePaidMediaPurchased], f ...Filter) Handle {
	h := &handle[UpdatePaidMediaPurchased]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypePaidMediaPurchased,
	}

	c.addHandler(UpdateTypePaidMediaPurchased, h)

	return h
}

// AddPendingTextMessageHandler registers a handler for UpdatePendingTextMessage updates.
func (c *Client) AddPendingTextMessageHandler(hn HandlerFunc[UpdatePendingTextMessage], f ...Filter) Handle {
	h := &handle[UpdatePendingTextMessage]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypePendingTextMessage,
	}

	c.addHandler(UpdateTypePendingTextMessage, h)

	return h
}

// AddPollHandler registers a handler for UpdatePoll updates.
func (c *Client) AddPollHandler(hn HandlerFunc[UpdatePoll], f ...Filter) Handle {
	h := &handle[UpdatePoll]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypePoll,
	}

	c.addHandler(UpdateTypePoll, h)

	return h
}

// AddPollAnswerHandler registers a handler for UpdatePollAnswer updates.
func (c *Client) AddPollAnswerHandler(hn HandlerFunc[UpdatePollAnswer], f ...Filter) Handle {
	h := &handle[UpdatePollAnswer]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypePollAnswer,
	}

	c.addHandler(UpdateTypePollAnswer, h)

	return h
}

// AddProfileAccentColorsHandler registers a handler for UpdateProfileAccentColors updates.
func (c *Client) AddProfileAccentColorsHandler(hn HandlerFunc[UpdateProfileAccentColors], f ...Filter) Handle {
	h := &handle[UpdateProfileAccentColors]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeProfileAccentColors,
	}

	c.addHandler(UpdateTypeProfileAccentColors, h)

	return h
}

// AddQuickReplyShortcutHandler registers a handler for UpdateQuickReplyShortcut updates.
func (c *Client) AddQuickReplyShortcutHandler(hn HandlerFunc[UpdateQuickReplyShortcut], f ...Filter) Handle {
	h := &handle[UpdateQuickReplyShortcut]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeQuickReplyShortcut,
	}

	c.addHandler(UpdateTypeQuickReplyShortcut, h)

	return h
}

// AddQuickReplyShortcutDeletedHandler registers a handler for UpdateQuickReplyShortcutDeleted updates.
func (c *Client) AddQuickReplyShortcutDeletedHandler(hn HandlerFunc[UpdateQuickReplyShortcutDeleted], f ...Filter) Handle {
	h := &handle[UpdateQuickReplyShortcutDeleted]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeQuickReplyShortcutDeleted,
	}

	c.addHandler(UpdateTypeQuickReplyShortcutDeleted, h)

	return h
}

// AddQuickReplyShortcutMessagesHandler registers a handler for UpdateQuickReplyShortcutMessages updates.
func (c *Client) AddQuickReplyShortcutMessagesHandler(hn HandlerFunc[UpdateQuickReplyShortcutMessages], f ...Filter) Handle {
	h := &handle[UpdateQuickReplyShortcutMessages]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeQuickReplyShortcutMessages,
	}

	c.addHandler(UpdateTypeQuickReplyShortcutMessages, h)

	return h
}

// AddQuickReplyShortcutsHandler registers a handler for UpdateQuickReplyShortcuts updates.
func (c *Client) AddQuickReplyShortcutsHandler(hn HandlerFunc[UpdateQuickReplyShortcuts], f ...Filter) Handle {
	h := &handle[UpdateQuickReplyShortcuts]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeQuickReplyShortcuts,
	}

	c.addHandler(UpdateTypeQuickReplyShortcuts, h)

	return h
}

// AddReactionNotificationSettingsHandler registers a handler for UpdateReactionNotificationSettings updates.
func (c *Client) AddReactionNotificationSettingsHandler(hn HandlerFunc[UpdateReactionNotificationSettings], f ...Filter) Handle {
	h := &handle[UpdateReactionNotificationSettings]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeReactionNotificationSettings,
	}

	c.addHandler(UpdateTypeReactionNotificationSettings, h)

	return h
}

// AddRecentStickersHandler registers a handler for UpdateRecentStickers updates.
func (c *Client) AddRecentStickersHandler(hn HandlerFunc[UpdateRecentStickers], f ...Filter) Handle {
	h := &handle[UpdateRecentStickers]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeRecentStickers,
	}

	c.addHandler(UpdateTypeRecentStickers, h)

	return h
}

// AddSavedAnimationsHandler registers a handler for UpdateSavedAnimations updates.
func (c *Client) AddSavedAnimationsHandler(hn HandlerFunc[UpdateSavedAnimations], f ...Filter) Handle {
	h := &handle[UpdateSavedAnimations]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeSavedAnimations,
	}

	c.addHandler(UpdateTypeSavedAnimations, h)

	return h
}

// AddSavedMessagesTagsHandler registers a handler for UpdateSavedMessagesTags updates.
func (c *Client) AddSavedMessagesTagsHandler(hn HandlerFunc[UpdateSavedMessagesTags], f ...Filter) Handle {
	h := &handle[UpdateSavedMessagesTags]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeSavedMessagesTags,
	}

	c.addHandler(UpdateTypeSavedMessagesTags, h)

	return h
}

// AddSavedMessagesTopicHandler registers a handler for UpdateSavedMessagesTopic updates.
func (c *Client) AddSavedMessagesTopicHandler(hn HandlerFunc[UpdateSavedMessagesTopic], f ...Filter) Handle {
	h := &handle[UpdateSavedMessagesTopic]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeSavedMessagesTopic,
	}

	c.addHandler(UpdateTypeSavedMessagesTopic, h)

	return h
}

// AddSavedMessagesTopicCountHandler registers a handler for UpdateSavedMessagesTopicCount updates.
func (c *Client) AddSavedMessagesTopicCountHandler(hn HandlerFunc[UpdateSavedMessagesTopicCount], f ...Filter) Handle {
	h := &handle[UpdateSavedMessagesTopicCount]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeSavedMessagesTopicCount,
	}

	c.addHandler(UpdateTypeSavedMessagesTopicCount, h)

	return h
}

// AddSavedNotificationSoundsHandler registers a handler for UpdateSavedNotificationSounds updates.
func (c *Client) AddSavedNotificationSoundsHandler(hn HandlerFunc[UpdateSavedNotificationSounds], f ...Filter) Handle {
	h := &handle[UpdateSavedNotificationSounds]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeSavedNotificationSounds,
	}

	c.addHandler(UpdateTypeSavedNotificationSounds, h)

	return h
}

// AddScopeNotificationSettingsHandler registers a handler for UpdateScopeNotificationSettings updates.
func (c *Client) AddScopeNotificationSettingsHandler(hn HandlerFunc[UpdateScopeNotificationSettings], f ...Filter) Handle {
	h := &handle[UpdateScopeNotificationSettings]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeScopeNotificationSettings,
	}

	c.addHandler(UpdateTypeScopeNotificationSettings, h)

	return h
}

// AddSecretChatHandler registers a handler for UpdateSecretChat updates.
func (c *Client) AddSecretChatHandler(hn HandlerFunc[UpdateSecretChat], f ...Filter) Handle {
	h := &handle[UpdateSecretChat]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeSecretChat,
	}

	c.addHandler(UpdateTypeSecretChat, h)

	return h
}

// AddServiceNotificationHandler registers a handler for UpdateServiceNotification updates.
func (c *Client) AddServiceNotificationHandler(hn HandlerFunc[UpdateServiceNotification], f ...Filter) Handle {
	h := &handle[UpdateServiceNotification]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeServiceNotification,
	}

	c.addHandler(UpdateTypeServiceNotification, h)

	return h
}

// AddSpeechRecognitionTrialHandler registers a handler for UpdateSpeechRecognitionTrial updates.
func (c *Client) AddSpeechRecognitionTrialHandler(hn HandlerFunc[UpdateSpeechRecognitionTrial], f ...Filter) Handle {
	h := &handle[UpdateSpeechRecognitionTrial]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeSpeechRecognitionTrial,
	}

	c.addHandler(UpdateTypeSpeechRecognitionTrial, h)

	return h
}

// AddSpeedLimitNotificationHandler registers a handler for UpdateSpeedLimitNotification updates.
func (c *Client) AddSpeedLimitNotificationHandler(hn HandlerFunc[UpdateSpeedLimitNotification], f ...Filter) Handle {
	h := &handle[UpdateSpeedLimitNotification]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeSpeedLimitNotification,
	}

	c.addHandler(UpdateTypeSpeedLimitNotification, h)

	return h
}

// AddStakeDiceStateHandler registers a handler for UpdateStakeDiceState updates.
func (c *Client) AddStakeDiceStateHandler(hn HandlerFunc[UpdateStakeDiceState], f ...Filter) Handle {
	h := &handle[UpdateStakeDiceState]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeStakeDiceState,
	}

	c.addHandler(UpdateTypeStakeDiceState, h)

	return h
}

// AddStarRevenueStatusHandler registers a handler for UpdateStarRevenueStatus updates.
func (c *Client) AddStarRevenueStatusHandler(hn HandlerFunc[UpdateStarRevenueStatus], f ...Filter) Handle {
	h := &handle[UpdateStarRevenueStatus]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeStarRevenueStatus,
	}

	c.addHandler(UpdateTypeStarRevenueStatus, h)

	return h
}

// AddStickerSetHandler registers a handler for UpdateStickerSet updates.
func (c *Client) AddStickerSetHandler(hn HandlerFunc[UpdateStickerSet], f ...Filter) Handle {
	h := &handle[UpdateStickerSet]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeStickerSet,
	}

	c.addHandler(UpdateTypeStickerSet, h)

	return h
}

// AddStoryHandler registers a handler for UpdateStory updates.
func (c *Client) AddStoryHandler(hn HandlerFunc[UpdateStory], f ...Filter) Handle {
	h := &handle[UpdateStory]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeStory,
	}

	c.addHandler(UpdateTypeStory, h)

	return h
}

// AddStoryDeletedHandler registers a handler for UpdateStoryDeleted updates.
func (c *Client) AddStoryDeletedHandler(hn HandlerFunc[UpdateStoryDeleted], f ...Filter) Handle {
	h := &handle[UpdateStoryDeleted]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeStoryDeleted,
	}

	c.addHandler(UpdateTypeStoryDeleted, h)

	return h
}

// AddStoryListChatCountHandler registers a handler for UpdateStoryListChatCount updates.
func (c *Client) AddStoryListChatCountHandler(hn HandlerFunc[UpdateStoryListChatCount], f ...Filter) Handle {
	h := &handle[UpdateStoryListChatCount]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeStoryListChatCount,
	}

	c.addHandler(UpdateTypeStoryListChatCount, h)

	return h
}

// AddStoryPostFailedHandler registers a handler for UpdateStoryPostFailed updates.
func (c *Client) AddStoryPostFailedHandler(hn HandlerFunc[UpdateStoryPostFailed], f ...Filter) Handle {
	h := &handle[UpdateStoryPostFailed]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeStoryPostFailed,
	}

	c.addHandler(UpdateTypeStoryPostFailed, h)

	return h
}

// AddStoryPostSucceededHandler registers a handler for UpdateStoryPostSucceeded updates.
func (c *Client) AddStoryPostSucceededHandler(hn HandlerFunc[UpdateStoryPostSucceeded], f ...Filter) Handle {
	h := &handle[UpdateStoryPostSucceeded]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeStoryPostSucceeded,
	}

	c.addHandler(UpdateTypeStoryPostSucceeded, h)

	return h
}

// AddStoryStealthModeHandler registers a handler for UpdateStoryStealthMode updates.
func (c *Client) AddStoryStealthModeHandler(hn HandlerFunc[UpdateStoryStealthMode], f ...Filter) Handle {
	h := &handle[UpdateStoryStealthMode]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeStoryStealthMode,
	}

	c.addHandler(UpdateTypeStoryStealthMode, h)

	return h
}

// AddSuggestedActionsHandler registers a handler for UpdateSuggestedActions updates.
func (c *Client) AddSuggestedActionsHandler(hn HandlerFunc[UpdateSuggestedActions], f ...Filter) Handle {
	h := &handle[UpdateSuggestedActions]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeSuggestedActions,
	}

	c.addHandler(UpdateTypeSuggestedActions, h)

	return h
}

// AddSupergroupHandler registers a handler for UpdateSupergroup updates.
func (c *Client) AddSupergroupHandler(hn HandlerFunc[UpdateSupergroup], f ...Filter) Handle {
	h := &handle[UpdateSupergroup]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeSupergroup,
	}

	c.addHandler(UpdateTypeSupergroup, h)

	return h
}

// AddSupergroupFullInfoHandler registers a handler for UpdateSupergroupFullInfo updates.
func (c *Client) AddSupergroupFullInfoHandler(hn HandlerFunc[UpdateSupergroupFullInfo], f ...Filter) Handle {
	h := &handle[UpdateSupergroupFullInfo]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeSupergroupFullInfo,
	}

	c.addHandler(UpdateTypeSupergroupFullInfo, h)

	return h
}

// AddTermsOfServiceHandler registers a handler for UpdateTermsOfService updates.
func (c *Client) AddTermsOfServiceHandler(hn HandlerFunc[UpdateTermsOfService], f ...Filter) Handle {
	h := &handle[UpdateTermsOfService]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeTermsOfService,
	}

	c.addHandler(UpdateTypeTermsOfService, h)

	return h
}

// AddTextCompositionStylesHandler registers a handler for UpdateTextCompositionStyles updates.
func (c *Client) AddTextCompositionStylesHandler(hn HandlerFunc[UpdateTextCompositionStyles], f ...Filter) Handle {
	h := &handle[UpdateTextCompositionStyles]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeTextCompositionStyles,
	}

	c.addHandler(UpdateTypeTextCompositionStyles, h)

	return h
}

// AddTonRevenueStatusHandler registers a handler for UpdateTonRevenueStatus updates.
func (c *Client) AddTonRevenueStatusHandler(hn HandlerFunc[UpdateTonRevenueStatus], f ...Filter) Handle {
	h := &handle[UpdateTonRevenueStatus]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeTonRevenueStatus,
	}

	c.addHandler(UpdateTypeTonRevenueStatus, h)

	return h
}

// AddTopicMessageCountHandler registers a handler for UpdateTopicMessageCount updates.
func (c *Client) AddTopicMessageCountHandler(hn HandlerFunc[UpdateTopicMessageCount], f ...Filter) Handle {
	h := &handle[UpdateTopicMessageCount]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeTopicMessageCount,
	}

	c.addHandler(UpdateTypeTopicMessageCount, h)

	return h
}

// AddTrendingStickerSetsHandler registers a handler for UpdateTrendingStickerSets updates.
func (c *Client) AddTrendingStickerSetsHandler(hn HandlerFunc[UpdateTrendingStickerSets], f ...Filter) Handle {
	h := &handle[UpdateTrendingStickerSets]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeTrendingStickerSets,
	}

	c.addHandler(UpdateTypeTrendingStickerSets, h)

	return h
}

// AddTrustedMiniAppBotsHandler registers a handler for UpdateTrustedMiniAppBots updates.
func (c *Client) AddTrustedMiniAppBotsHandler(hn HandlerFunc[UpdateTrustedMiniAppBots], f ...Filter) Handle {
	h := &handle[UpdateTrustedMiniAppBots]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeTrustedMiniAppBots,
	}

	c.addHandler(UpdateTypeTrustedMiniAppBots, h)

	return h
}

// AddUnconfirmedSessionHandler registers a handler for UpdateUnconfirmedSession updates.
func (c *Client) AddUnconfirmedSessionHandler(hn HandlerFunc[UpdateUnconfirmedSession], f ...Filter) Handle {
	h := &handle[UpdateUnconfirmedSession]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeUnconfirmedSession,
	}

	c.addHandler(UpdateTypeUnconfirmedSession, h)

	return h
}

// AddUnreadChatCountHandler registers a handler for UpdateUnreadChatCount updates.
func (c *Client) AddUnreadChatCountHandler(hn HandlerFunc[UpdateUnreadChatCount], f ...Filter) Handle {
	h := &handle[UpdateUnreadChatCount]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeUnreadChatCount,
	}

	c.addHandler(UpdateTypeUnreadChatCount, h)

	return h
}

// AddUnreadMessageCountHandler registers a handler for UpdateUnreadMessageCount updates.
func (c *Client) AddUnreadMessageCountHandler(hn HandlerFunc[UpdateUnreadMessageCount], f ...Filter) Handle {
	h := &handle[UpdateUnreadMessageCount]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeUnreadMessageCount,
	}

	c.addHandler(UpdateTypeUnreadMessageCount, h)

	return h
}

// AddUserHandler registers a handler for UpdateUser updates.
func (c *Client) AddUserHandler(hn HandlerFunc[UpdateUser], f ...Filter) Handle {
	h := &handle[UpdateUser]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeUser,
	}

	c.addHandler(UpdateTypeUser, h)

	return h
}

// AddUserFullInfoHandler registers a handler for UpdateUserFullInfo updates.
func (c *Client) AddUserFullInfoHandler(hn HandlerFunc[UpdateUserFullInfo], f ...Filter) Handle {
	h := &handle[UpdateUserFullInfo]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeUserFullInfo,
	}

	c.addHandler(UpdateTypeUserFullInfo, h)

	return h
}

// AddUserPrivacySettingRulesHandler registers a handler for UpdateUserPrivacySettingRules updates.
func (c *Client) AddUserPrivacySettingRulesHandler(hn HandlerFunc[UpdateUserPrivacySettingRules], f ...Filter) Handle {
	h := &handle[UpdateUserPrivacySettingRules]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeUserPrivacySettingRules,
	}

	c.addHandler(UpdateTypeUserPrivacySettingRules, h)

	return h
}

// AddUserStatusHandler registers a handler for UpdateUserStatus updates.
func (c *Client) AddUserStatusHandler(hn HandlerFunc[UpdateUserStatus], f ...Filter) Handle {
	h := &handle[UpdateUserStatus]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeUserStatus,
	}

	c.addHandler(UpdateTypeUserStatus, h)

	return h
}

// AddVideoPublishedHandler registers a handler for UpdateVideoPublished updates.
func (c *Client) AddVideoPublishedHandler(hn HandlerFunc[UpdateVideoPublished], f ...Filter) Handle {
	h := &handle[UpdateVideoPublished]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeVideoPublished,
	}

	c.addHandler(UpdateTypeVideoPublished, h)

	return h
}

// AddWebAppMessageSentHandler registers a handler for UpdateWebAppMessageSent updates.
func (c *Client) AddWebAppMessageSentHandler(hn HandlerFunc[UpdateWebAppMessageSent], f ...Filter) Handle {
	h := &handle[UpdateWebAppMessageSent]{
		client:  c,
		handler: hn,
		filters: f,
		tp:      UpdateTypeWebAppMessageSent,
	}

	c.addHandler(UpdateTypeWebAppMessageSent, h)

	return h
}

func ExtractChatID(u TlObject) int64 {
	switch upd := u.(type) {
	case *UpdateAnimatedEmojiMessageClicked:
		return upd.ChatId
	case *UpdateBusinessMessagesDeleted:
		return upd.ChatId
	case *UpdateChatAccentColors:
		return upd.ChatId
	case *UpdateChatAction:
		return upd.ChatId
	case *UpdateChatActionBar:
		return upd.ChatId
	case *UpdateChatAddedToList:
		return upd.ChatId
	case *UpdateChatAvailableReactions:
		return upd.ChatId
	case *UpdateChatBackground:
		return upd.ChatId
	case *UpdateChatBlockList:
		return upd.ChatId
	case *UpdateChatBoost:
		return upd.ChatId
	case *UpdateChatBusinessBotManageBar:
		return upd.ChatId
	case *UpdateChatDefaultDisableNotification:
		return upd.ChatId
	case *UpdateChatDraftMessage:
		return upd.ChatId
	case *UpdateChatEmojiStatus:
		return upd.ChatId
	case *UpdateChatHasProtectedContent:
		return upd.ChatId
	case *UpdateChatHasScheduledMessages:
		return upd.ChatId
	case *UpdateChatIsMarkedAsUnread:
		return upd.ChatId
	case *UpdateChatIsTranslatable:
		return upd.ChatId
	case *UpdateChatLastMessage:
		return upd.ChatId
	case *UpdateChatMember:
		return upd.ChatId
	case *UpdateChatMessageAutoDeleteTime:
		return upd.ChatId
	case *UpdateChatMessageSender:
		return upd.ChatId
	case *UpdateChatNotificationSettings:
		return upd.ChatId
	case *UpdateChatOnlineMemberCount:
		return upd.ChatId
	case *UpdateChatPendingJoinRequests:
		return upd.ChatId
	case *UpdateChatPermissions:
		return upd.ChatId
	case *UpdateChatPhoto:
		return upd.ChatId
	case *UpdateChatPosition:
		return upd.ChatId
	case *UpdateChatReadInbox:
		return upd.ChatId
	case *UpdateChatReadOutbox:
		return upd.ChatId
	case *UpdateChatRemovedFromList:
		return upd.ChatId
	case *UpdateChatReplyMarkup:
		return upd.ChatId
	case *UpdateChatRevenueAmount:
		return upd.ChatId
	case *UpdateChatTheme:
		return upd.ChatId
	case *UpdateChatTitle:
		return upd.ChatId
	case *UpdateChatUnreadMentionCount:
		return upd.ChatId
	case *UpdateChatUnreadPollVoteCount:
		return upd.ChatId
	case *UpdateChatUnreadReactionCount:
		return upd.ChatId
	case *UpdateChatVideoChat:
		return upd.ChatId
	case *UpdateChatViewAsTopics:
		return upd.ChatId
	case *UpdateDeleteMessages:
		return upd.ChatId
	case *UpdateForumTopic:
		return upd.ChatId
	case *UpdateManagedBot:
		return upd.UserId
	case *UpdateMessageContainsUnreadPollVotes:
		return upd.ChatId
	case *UpdateMessageContent:
		return upd.ChatId
	case *UpdateMessageContentOpened:
		return upd.ChatId
	case *UpdateMessageEdited:
		return upd.ChatId
	case *UpdateMessageFactCheck:
		return upd.ChatId
	case *UpdateMessageInteractionInfo:
		return upd.ChatId
	case *UpdateMessageIsPinned:
		return upd.ChatId
	case *UpdateMessageLiveLocationViewed:
		return upd.ChatId
	case *UpdateMessageMentionRead:
		return upd.ChatId
	case *UpdateMessageReaction:
		return upd.ChatId
	case *UpdateMessageReactions:
		return upd.ChatId
	case *UpdateMessageSendAcknowledged:
		return upd.ChatId
	case *UpdateMessageSendFailed:
		if upd.Message != nil {
			return upd.Message.ChatId
		}
	case *UpdateMessageSendSucceeded:
		if upd.Message != nil {
			return upd.Message.ChatId
		}
	case *UpdateMessageSuggestedPostInfo:
		return upd.ChatId
	case *UpdateMessageUnreadReactions:
		return upd.ChatId
	case *UpdateNewBusinessCallbackQuery:
		return upd.SenderUserId
	case *UpdateNewCallbackQuery:
		return upd.ChatId
	case *UpdateNewChat:
		if upd.Chat != nil {
			return upd.Chat.Id
		}
	case *UpdateNewChatJoinRequest:
		return upd.ChatId
	case *UpdateNewChosenInlineResult:
		return upd.SenderUserId
	case *UpdateNewGroupCallPaidReaction:
		if up, ok := upd.SenderId.(*MessageSenderUser); ok {
			return up.UserId
		}
		if up, ok := upd.SenderId.(*MessageSenderChat); ok {
			return up.ChatId
		}
	case *UpdateNewGuestQuery:
		if upd.Message != nil {
			return upd.Message.ChatId
		}
	case *UpdateNewInlineCallbackQuery:
		return upd.SenderUserId
	case *UpdateNewInlineQuery:
		return upd.SenderUserId
	case *UpdateNewMessage:
		if upd.Message != nil {
			return upd.Message.ChatId
		}
	case *UpdateNewPreCheckoutQuery:
		return upd.SenderUserId
	case *UpdateNewShippingQuery:
		return upd.SenderUserId
	case *UpdateNotificationGroup:
		return upd.ChatId
	case *UpdatePaidMediaPurchased:
		return upd.UserId
	case *UpdatePendingTextMessage:
		return upd.ChatId
	case *UpdateTopicMessageCount:
		return upd.ChatId
	case *UpdateUser:
		if upd.User != nil {
			return upd.User.Id
		}
	case *UpdateUserFullInfo:
		return upd.UserId
	case *UpdateUserStatus:
		return upd.UserId
	case *UpdateVideoPublished:
		return upd.ChatId
	}
	return 0
}

func ExtractSenderID(u TlObject) int64 {
	switch upd := u.(type) {
	case *UpdateChatAction:
		if up, ok := upd.SenderId.(*MessageSenderUser); ok {
			return up.UserId
		}
		if up, ok := upd.SenderId.(*MessageSenderChat); ok {
			return up.ChatId
		}
	case *UpdateManagedBot:
		return upd.UserId
	case *UpdateMessageSendFailed:
		if upd.Message != nil {
			return upd.Message.SenderID()
		}
	case *UpdateMessageSendSucceeded:
		if upd.Message != nil {
			return upd.Message.SenderID()
		}
	case *UpdateNewBusinessCallbackQuery:
		return upd.SenderUserId
	case *UpdateNewCallbackQuery:
		return upd.SenderUserId
	case *UpdateNewChosenInlineResult:
		return upd.SenderUserId
	case *UpdateNewGroupCallPaidReaction:
		if up, ok := upd.SenderId.(*MessageSenderUser); ok {
			return up.UserId
		}
		if up, ok := upd.SenderId.(*MessageSenderChat); ok {
			return up.ChatId
		}
	case *UpdateNewGuestQuery:
		if upd.Message != nil {
			return upd.Message.SenderID()
		}
	case *UpdateNewInlineCallbackQuery:
		return upd.SenderUserId
	case *UpdateNewInlineQuery:
		return upd.SenderUserId
	case *UpdateNewMessage:
		if upd.Message != nil {
			return upd.Message.SenderID()
		}
	case *UpdateNewPreCheckoutQuery:
		return upd.SenderUserId
	case *UpdateNewShippingQuery:
		return upd.SenderUserId
	case *UpdatePaidMediaPurchased:
		return upd.UserId
	case *UpdateUserFullInfo:
		return upd.UserId
	case *UpdateUserStatus:
		return upd.UserId
	}
	return 0
}
